<div class="top_menu">    
    <a href="./">&#127968; Home</a>&nbsp;
     | &nbsp;
    <a href="./entityView.php?app=_system&table=seed_apps ">&#9881; Apps</a>&nbsp;
     | &nbsp;
    <!--a href="./jobs.php">&#9881; Jobs</a-->
     
    <a href="./entityView.php?app=_system&table=seed_menus ">&#9108; Menus</a>&nbsp;
     | &nbsp;
    <a href="./entityView.php?app=_system&table=seed_nomenclatures ">&#9733; Nomenclatures</a>&nbsp;
     | &nbsp;
    <a href="./entityView.php?app=_system&table=seed_app_reports ">&#128462; Reports</a>&nbsp;
     | &nbsp;
     <a target="_blank" href="https://data-seed.tech/tutorial.php">&#128712; Help</a>
</div><br><br>